[package]
name = "kvcounter-actor"
version = "0.3.3"
authors = [ "wasmcloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
form_urlencoded = "1.0"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
wit-bindgen-rust = { version = "0.1", git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "f8d4e9c63c8abb9dd08b83b9197cbaf7cc4daa19" }
